### ISSUE TITLE
[WIP] Questions/Brainstorming

### ISSUE THREAD

**Issue by GretaCB** [mapbox/node-cpp-skel#50]
Per discussion with @springmeyer , outlining possible next steps for node-cpp-skel and capturing best practices to document and integrate into the skel design.

## Questions to answer
- What does it look like to have the variable that represents an instance of a class accessible in the threadpool?

- What is the role of a singleton and how is it related to other design patterns for sync/async?

- When passing data to thread pool, the data needs to be a type that is safe to pass into the thread pool. What makes a type safe to pass into the thread pool? 
  - Two scenarios that are safe: 
    - Copy data to a C++ object (pure, part of the C++ std lib...not V8)
    - Copy V8 data: Extra work to keep the V8 object alive, avoids the object perhaps getting deleted (trick: use v8::Persistant)

### Goal 1)
- Provide examples of objects that feel real-world, actionable, and sturdy
- Unlocks: ability to fork and run fast and feel confidence the foundation is a best practice

### Goal 2)
- Provide incremental examples that build complexity gradually
- Unlocks: easier for beginning developers to understand gradually why extra complexity is needed

**Preliminary conclusion: object-sync is caught between these worlds**
 
 

## Terms to learn
- [ ] @gretacb to add to cpp glossary

### Standard C++
- Singleton - is a general programming concept for creating a instance once in the process
  - mapnik uses singletons for datasource plugin and font registration
- `static` keyword
- reference (what does the `&` mean?)

### V8
- `Nan::Persistent` (which is really `v8::Persistent`)
- `v8::FunctionTemplate` and `v8::Function`
- `Nan::ObjectWrap`

## Possible next steps:
- [x] @springmeyer could add/edit comments and provide them in another PR
- [x] Build ^^ items into the cpp glossary (@gretacb first pass)
- [x] [Object async example](https://github.com/mapbox/node-cpp-skel/pull/52): Demonstrate how we safely and efficiently utilize the threadpool to do work on data.
  Two options:
  - vt-shaver example:
    - Filters class, exposed in JS
    - Able to create the Filters class once (as object in JS)
    - Standalone `shave` function access Filters as an argument
    - Filters is passed into the threadpool
  - node-mapnik design: Classes expose method

**Comment by GretaCB** [comment]
### Update

Per chat with @springmeyer when running through https://github.com/mapbox/node-cpp-skel/pull/51, I plan to split the README into different docs:
- Reference: Info about C++ best practices, add-on conventions, and general 101
- Template: The main README will be a great template README that developers can use for their own add-ons when using the skel as a baseline (how to install, run tests, build, publish, etc)

**Comment by springmeyer** [comment]
> Build ^^ items into the cpp glossary (@GretaCB first pass)

https://github.com/mapbox/cpp/commit/92af06817b7f7df1506fdd696b6359e95e3fc476 and https://github.com/mapbox/cpp/commit/beb75bfde7ead41aab53d0520cd53ab1c27729b6

**Comment by springmeyer** [comment]
@GretaCB thanks for catching up on skel today voice. To help get to the finish line for this phase I've reviewed all open issues and commented on ones that I think are actionable. Of those that are actionable I think these are the priority things to finish before you move along:

- [ ] Finish docs re-org: https://github.com/mapbox/node-cpp-skel/pull/53
- [ ] Add support for code formatting and asserting on correct format: https://github.com/mapbox/node-cpp-skel/issues/37#issuecomment-319539643
- [ ] Land this improvement for handling strings: https://github.com/mapbox/node-cpp-skel/issues/54
- [ ] Quick check to make sure the sanitizers are working on travis: https://github.com/mapbox/node-cpp-skel/issues/40#issuecomment-319525532
- [ ] Land the first phase of benchmark scripts in node-cpp-skel master: https://github.com/mapbox/node-cpp-skel/pull/29#issuecomment-319533657

**Comment by springmeyer** [comment]
woot @GretaCB - everything above is checked. Shall we close?
